# -*- coding: utf-8 -*-
"""Mapeo de nombres de equipos.

Nombre canonico = el usado por el historico de entrenamiento
(github.com/martj42/international_results, results.csv).
"""

# Espanol (como aparece en la polla) -> canonico ingles (results.csv)
TEAMS_ES_EN = {
    "Alemania": "Germany",
    "Arabia Saudita": "Saudi Arabia",
    "Argelia": "Algeria",
    "Argentina": "Argentina",
    "Australia": "Australia",
    "Austria": "Austria",
    "Bélgica": "Belgium",
    "Bosnia-Herzegovina": "Bosnia and Herzegovina",
    "Brasil": "Brazil",
    "Cabo Verde": "Cape Verde",
    "Canadá": "Canada",
    "Catar": "Qatar",
    "Colombia": "Colombia",
    "Corea del Sur": "South Korea",
    "Costa de Marfil": "Ivory Coast",
    "Croacia": "Croatia",
    "Curazao": "Curaçao",
    "Ecuador": "Ecuador",
    "Egipto": "Egypt",
    "Escocia": "Scotland",
    "España": "Spain",
    "Estados Unidos": "United States",
    "Francia": "France",
    "Ghana": "Ghana",
    "Haití": "Haiti",
    "Inglaterra": "England",
    "Irak": "Iraq",
    "Irán": "Iran",
    "Japón": "Japan",
    "Jordania": "Jordan",
    "Marruecos": "Morocco",
    "México": "Mexico",
    "Noruega": "Norway",
    "Nueva Zelanda": "New Zealand",
    "Países Bajos": "Netherlands",
    "Panamá": "Panama",
    "Paraguay": "Paraguay",
    "Portugal": "Portugal",
    "RD Congo": "DR Congo",
    "República Checa": "Czech Republic",
    "Senegal": "Senegal",
    "Sudáfrica": "South Africa",
    "Suecia": "Sweden",
    "Suiza": "Switzerland",
    "Túnez": "Tunisia",
    "Turquía": "Turkey",
    "Uruguay": "Uruguay",
    "Uzbekistán": "Uzbekistan",
}

TEAMS_EN_ES = {en: es for es, en in TEAMS_ES_EN.items()}

OPENFOOTBALL_TO_CANON = {
    # openfootball
    "USA": "United States",
    "Bosnia & Herzegovina": "Bosnia and Herzegovina",
    "Türkiye": "Turkey",
    "Czechia": "Czech Republic",
    "Korea Republic": "South Korea",
    "Côte d'Ivoire": "Ivory Coast",
    # ESPN (los que difieren del canónico)
    "Bosnia-Herzegovina": "Bosnia and Herzegovina",
    "Congo DR": "DR Congo",
}


def canon(name: str) -> str:
    """Normaliza cualquier nombre (openfootball/es/canonico) al canonico."""
    if name in OPENFOOTBALL_TO_CANON:
        return OPENFOOTBALL_TO_CANON[name]
    if name in TEAMS_ES_EN:
        return TEAMS_ES_EN[name]
    return name


HOST_BY_CITY_KEYWORD = {
    "Mexico City": "Mexico",
    "Guadalajara": "Mexico",
    "Monterrey": "Mexico",
    "Toronto": "Canada",
    "Vancouver": "Canada",
}
DEFAULT_HOST = "United States"


def host_country(ground: str) -> str:
    for kw, country in HOST_BY_CITY_KEYWORD.items():
        if kw in ground:
            return country
    return DEFAULT_HOST


CONFED = {
    "Austria": "UEFA",
    "Belgium": "UEFA",
    "Bosnia and Herzegovina": "UEFA",
    "Croatia": "UEFA",
    "Czech Republic": "UEFA",
    "England": "UEFA",
    "France": "UEFA",
    "Germany": "UEFA",
    "Netherlands": "UEFA",
    "Norway": "UEFA",
    "Portugal": "UEFA",
    "Scotland": "UEFA",
    "Spain": "UEFA",
    "Sweden": "UEFA",
    "Switzerland": "UEFA",
    "Turkey": "UEFA",
    "Argentina": "CONMEBOL",
    "Brazil": "CONMEBOL",
    "Colombia": "CONMEBOL",
    "Ecuador": "CONMEBOL",
    "Paraguay": "CONMEBOL",
    "Uruguay": "CONMEBOL",
    "Canada": "CONCACAF",
    "Curaçao": "CONCACAF",
    "Haiti": "CONCACAF",
    "Mexico": "CONCACAF",
    "Panama": "CONCACAF",
    "United States": "CONCACAF",
    "Algeria": "CAF",
    "Cape Verde": "CAF",
    "DR Congo": "CAF",
    "Egypt": "CAF",
    "Ghana": "CAF",
    "Ivory Coast": "CAF",
    "Morocco": "CAF",
    "Senegal": "CAF",
    "South Africa": "CAF",
    "Tunisia": "CAF",
    "Australia": "AFC",
    "Iran": "AFC",
    "Iraq": "AFC",
    "Japan": "AFC",
    "Jordan": "AFC",
    "Qatar": "AFC",
    "Saudi Arabia": "AFC",
    "South Korea": "AFC",
    "Uzbekistan": "AFC",
    "New Zealand": "OFC",
    "Italy": "UEFA",
    "Russia": "UEFA",
    "Poland": "UEFA",
    "Denmark": "UEFA",
    "Serbia": "UEFA",
    "Ukraine": "UEFA",
    "Wales": "UEFA",
    "Greece": "UEFA",
    "Hungary": "UEFA",
    "Romania": "UEFA",
    "Ireland": "UEFA",
    "Northern Ireland": "UEFA",
    "Slovakia": "UEFA",
    "Slovenia": "UEFA",
    "Finland": "UEFA",
    "Iceland": "UEFA",
    "Albania": "UEFA",
    "North Macedonia": "UEFA",
    "Bulgaria": "UEFA",
    "Israel": "UEFA",
    "Georgia": "UEFA",
    "Montenegro": "UEFA",
    "Kosovo": "UEFA",
    "Chile": "CONMEBOL",
    "Peru": "CONMEBOL",
    "Bolivia": "CONMEBOL",
    "Venezuela": "CONMEBOL",
    "Costa Rica": "CONCACAF",
    "Honduras": "CONCACAF",
    "Jamaica": "CONCACAF",
    "El Salvador": "CONCACAF",
    "Guatemala": "CONCACAF",
    "Trinidad and Tobago": "CONCACAF",
    "Suriname": "CONCACAF",
    "Nigeria": "CAF",
    "Cameroon": "CAF",
    "Mali": "CAF",
    "Burkina Faso": "CAF",
    "Guinea": "CAF",
    "Zambia": "CAF",
    "Gabon": "CAF",
    "Kenya": "CAF",
    "Uganda": "CAF",
    "Angola": "CAF",
    "Benin": "CAF",
    "Libya": "CAF",
    "Mozambique": "CAF",
    "Zimbabwe": "CAF",
    "Gambia": "CAF",
    "Equatorial Guinea": "CAF",
    "Mauritania": "CAF",
    "Madagascar": "CAF",
    "China PR": "AFC",
    "United Arab Emirates": "AFC",
    "Oman": "AFC",
    "Bahrain": "AFC",
    "Kuwait": "AFC",
    "Syria": "AFC",
    "Lebanon": "AFC",
    "Thailand": "AFC",
    "Vietnam": "AFC",
    "Indonesia": "AFC",
    "India": "AFC",
    "Malaysia": "AFC",
    "North Korea": "AFC",
    "Palestine": "AFC",
    "Kyrgyzstan": "AFC",
    "Tajikistan": "AFC",
    "Turkmenistan": "AFC",
    "Fiji": "OFC",
    "New Caledonia": "OFC",
    "Tahiti": "OFC",
    "Solomon Islands": "OFC",
    "Papua New Guinea": "OFC",
}

CONFED_CODES = {
    "UEFA": 0,
    "CONMEBOL": 1,
    "CONCACAF": 2,
    "CAF": 3,
    "AFC": 4,
    "OFC": 5,
    "OTHER": 6,
}


def confed_code(team: str) -> int:
    return CONFED_CODES[CONFED.get(team, "OTHER")]


FLAG_CODES = {
    "Algeria": "dz",
    "Argentina": "ar",
    "Australia": "au",
    "Austria": "at",
    "Belgium": "be",
    "Bosnia and Herzegovina": "ba",
    "Brazil": "br",
    "Canada": "ca",
    "Cape Verde": "cv",
    "Colombia": "co",
    "Croatia": "hr",
    "Curaçao": "cw",
    "Czech Republic": "cz",
    "DR Congo": "cd",
    "Ecuador": "ec",
    "Egypt": "eg",
    "England": "gb-eng",
    "France": "fr",
    "Germany": "de",
    "Ghana": "gh",
    "Haiti": "ht",
    "Iran": "ir",
    "Iraq": "iq",
    "Ivory Coast": "ci",
    "Japan": "jp",
    "Jordan": "jo",
    "Mexico": "mx",
    "Morocco": "ma",
    "Netherlands": "nl",
    "New Zealand": "nz",
    "Norway": "no",
    "Panama": "pa",
    "Paraguay": "py",
    "Portugal": "pt",
    "Qatar": "qa",
    "Saudi Arabia": "sa",
    "Scotland": "gb-sct",
    "Senegal": "sn",
    "South Africa": "za",
    "South Korea": "kr",
    "Spain": "es",
    "Sweden": "se",
    "Switzerland": "ch",
    "Tunisia": "tn",
    "Turkey": "tr",
    "United States": "us",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
}
